### ISSUE TITLE
Forcing wrong WrongInitialSolutionSelected

### ISSUE THREAD

**Issue by johanrhodin** [casella/FailureModes#1]
In `WrongInitialSolutionSelected` my Modelica tool choses `dp_pump` positive. Is there a handy way to force it to the wrong solution?

**Comment by casella** [comment]
You are right, I messed up a bit with this example. The most likely choice of iteration variable in this case is w_pump, so I applied a negative start modifier to that in 4ef316a, and thus got the convergence to the wrong solution on two different tools.

**Comment by johanrhodin** [comment]
Verified fix in SystemModeler
